#
# Makefile for the input core drivers.
#

 
obj-y  += txd_focaltech_ts.o
#focaltech_ts-objs += focaltech.o focaltech_ctl.o focaltech_ex_fun.o
txd_focaltech_ts-objs := focaltech.o
txd_focaltech_ts-objs += focaltech_ctl.o 
txd_focaltech_ts-objs += focaltech_ex_fun.o
#txd_focaltech_ts-objs += ft6x36_download_lib.a 
#txd_focaltech_ts-objs += ft_gesture_lib.a 
#txd_focaltech_ts-objs += ft_gesture1209V01_lib.a
#txd_focaltech_ts-y    += focaltech.o focaltech_ctl.o focaltech_ex_fun.o